// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type CourierStatus string

const (
	CourierStatusAvailable CourierStatus = "available"
	CourierStatusBusy      CourierStatus = "busy"
	CourierStatusOffline   CourierStatus = "offline"
)

func (e *CourierStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CourierStatus(s)
	case string:
		*e = CourierStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CourierStatus: %T", src)
	}
	return nil
}

type NullCourierStatus struct {
	CourierStatus CourierStatus
	Valid         bool // Valid is true if CourierStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCourierStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CourierStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CourierStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCourierStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CourierStatus), nil
}

type FacilityType string

const (
	FacilityTypeMegaGateway FacilityType = "mega_gateway"
	FacilityTypeRegionalHub FacilityType = "regional_hub"
	FacilityTypeLocalBranch FacilityType = "local_branch"
)

func (e *FacilityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FacilityType(s)
	case string:
		*e = FacilityType(s)
	default:
		return fmt.Errorf("unsupported scan type for FacilityType: %T", src)
	}
	return nil
}

type NullFacilityType struct {
	FacilityType FacilityType
	Valid        bool // Valid is true if FacilityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFacilityType) Scan(value interface{}) error {
	if value == nil {
		ns.FacilityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FacilityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFacilityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FacilityType), nil
}

type ShipmentStatus string

const (
	ShipmentStatusPendingPickup  ShipmentStatus = "pending_pickup"
	ShipmentStatusReadyForPickup ShipmentStatus = "ready_for_pickup"
	ShipmentStatusPickedUp       ShipmentStatus = "picked_up"
	ShipmentStatusInTransit      ShipmentStatus = "in_transit"
	ShipmentStatusArrivedAtHub   ShipmentStatus = "arrived_at_hub"
	ShipmentStatusOutForDelivery ShipmentStatus = "out_for_delivery"
	ShipmentStatusDelivered      ShipmentStatus = "delivered"
	ShipmentStatusFailedDelivery ShipmentStatus = "failed_delivery"
	ShipmentStatusRejected       ShipmentStatus = "rejected"
)

func (e *ShipmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShipmentStatus(s)
	case string:
		*e = ShipmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ShipmentStatus: %T", src)
	}
	return nil
}

type NullShipmentStatus struct {
	ShipmentStatus ShipmentStatus
	Valid          bool // Valid is true if ShipmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShipmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ShipmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShipmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShipmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShipmentStatus), nil
}

type UserRole string

const (
	UserRoleAdmin   UserRole = "admin"
	UserRoleCourier UserRole = "courier"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Courier struct {
	ID                int32
	UserID            int32
	FirstName         string
	LastName          string
	PhoneNumber       string
	VehicleType       string
	PlateNumber       string
	Status            CourierStatus
	CurrentFacilityID sql.NullInt16
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type DeliveryBoundary struct {
	ID           int32
	FacilityID   int32
	DeliveryArea interface{}
}

type Facility struct {
	ID          int32
	Name        string
	Type        FacilityType
	SortingCode string
	Address     string
	Location    interface{}
	ParentID    sql.NullInt32
	IsActive    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Parcel struct {
	ID                    int32
	TrackingNumber        string
	ExternalOrderID       string
	WeightGrams           int32
	OriginFacilityID      int32
	DestinationFacilityID int32
	CurrentFacilityID     sql.NullInt32
	SortingCodeCache      string
	RoutingPipelineCache  string
	StoreID               int32
	CustomerName          string
	CustomerAddress       string
	CustomerPhone         string
	CustomerLocation      interface{}
	AssignedCourierID     sql.NullInt32
	Status                ShipmentStatus
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type Store struct {
	ID            int32
	Name          string
	ContactNumber string
	Address       string
	Location      interface{}
}

type TrackingLog struct {
	ID          int32
	ParcelID    int32
	Status      ShipmentStatus
	Description string
	FacilityID  sql.NullInt32
	CourierID   sql.NullInt32
}

type User struct {
	ID        int32
	Email     string
	Password  string
	Role      UserRole
	CreatedAt time.Time
	UpdatedAt time.Time
}
