// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: query.sql

package db

import (
	"context"
)

const facilities = `-- name: Facilities :many
SELECT id, name
FROM facilities
`

type FacilitiesRow struct {
	ID   int32
	Name string
}

func (q *Queries) Facilities(ctx context.Context) ([]FacilitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, facilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FacilitiesRow
	for rows.Next() {
		var i FacilitiesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFacilityById = `-- name: GetFacilityById :one
SELECT id, name
FROM facilities
WHERE id = $1
`

type GetFacilityByIdRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetFacilityById(ctx context.Context, id int32) (GetFacilityByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getFacilityById, id)
	var i GetFacilityByIdRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
